/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages.pb-c.h"

void baud_rate__init
    (BaudRate *message) {
  static BaudRate init_value = BAUD_RATE__INIT;
  *message = init_value;
}

size_t baud_rate__get_packed_size
    (const BaudRate *message) {
  assert(message->base.descriptor == &baud_rate__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *) (message));
}

size_t baud_rate__pack
    (const BaudRate *message,
     uint8_t *out) {
  assert(message->base.descriptor == &baud_rate__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *) message, out);
}

size_t baud_rate__pack_to_buffer
    (const BaudRate *message,
     ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &baud_rate__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *) message, buffer);
}

BaudRate *
baud_rate__unpack
    (ProtobufCAllocator *allocator,
     size_t len,
     const uint8_t *data) {
  return (BaudRate *)
      protobuf_c_message_unpack(&baud_rate__descriptor,
                                allocator, len, data);
}

void baud_rate__free_unpacked
    (BaudRate *message,
     ProtobufCAllocator *allocator) {
  assert(message->base.descriptor == &baud_rate__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *) message, allocator);
}

void frame__init
    (Frame *message) {
  static Frame init_value = FRAME__INIT;
  *message = init_value;
}

size_t frame__get_packed_size
    (const Frame *message) {
  assert(message->base.descriptor == &frame__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *) (message));
}

size_t frame__pack
    (const Frame *message,
     uint8_t *out) {
  assert(message->base.descriptor == &frame__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *) message, out);
}

size_t frame__pack_to_buffer
    (const Frame *message,
     ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &frame__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *) message, buffer);
}

Frame *
frame__unpack
    (ProtobufCAllocator *allocator,
     size_t len,
     const uint8_t *data) {
  return (Frame *)
      protobuf_c_message_unpack(&frame__descriptor,
                                allocator, len, data);
}

void frame__free_unpacked
    (Frame *message,
     ProtobufCAllocator *allocator) {
  assert(message->base.descriptor == &frame__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *) message, allocator);
}

void to_device__init
    (ToDevice *message) {
  static ToDevice init_value = TO_DEVICE__INIT;
  *message = init_value;
}

size_t to_device__get_packed_size
    (const ToDevice *message) {
  assert(message->base.descriptor == &to_device__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *) (message));
}

size_t to_device__pack
    (const ToDevice *message,
     uint8_t *out) {
  assert(message->base.descriptor == &to_device__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *) message, out);
}

size_t to_device__pack_to_buffer
    (const ToDevice *message,
     ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &to_device__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *) message, buffer);
}

ToDevice *
to_device__unpack
    (ProtobufCAllocator *allocator,
     size_t len,
     const uint8_t *data) {
  return (ToDevice *)
      protobuf_c_message_unpack(&to_device__descriptor,
                                allocator, len, data);
}

void to_device__free_unpacked
    (ToDevice *message,
     ProtobufCAllocator *allocator) {
  assert(message->base.descriptor == &to_device__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *) message, allocator);
}

void response__init
    (Response *message) {
  static Response init_value = RESPONSE__INIT;
  *message = init_value;
}

size_t response__get_packed_size
    (const Response *message) {
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *) (message));
}

size_t response__pack
    (const Response *message,
     uint8_t *out) {
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *) message, out);
}

size_t response__pack_to_buffer
    (const Response *message,
     ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *) message, buffer);
}

Response *
response__unpack
    (ProtobufCAllocator *allocator,
     size_t len,
     const uint8_t *data) {
  return (Response *)
      protobuf_c_message_unpack(&response__descriptor,
                                allocator, len, data);
}

void response__free_unpacked
    (Response *message,
     ProtobufCAllocator *allocator) {
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *) message, allocator);
}

void status__init
    (Status *message) {
  static Status init_value = STATUS__INIT;
  *message = init_value;
}

size_t status__get_packed_size
    (const Status *message) {
  assert(message->base.descriptor == &status__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *) (message));
}

size_t status__pack
    (const Status *message,
     uint8_t *out) {
  assert(message->base.descriptor == &status__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *) message, out);
}

size_t status__pack_to_buffer
    (const Status *message,
     ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &status__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *) message, buffer);
}

Status *
status__unpack
    (ProtobufCAllocator *allocator,
     size_t len,
     const uint8_t *data) {
  return (Status *)
      protobuf_c_message_unpack(&status__descriptor,
                                allocator, len, data);
}

void status__free_unpacked
    (Status *message,
     ProtobufCAllocator *allocator) {
  assert(message->base.descriptor == &status__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *) message, allocator);
}

void from_device__init
    (FromDevice *message) {
  static FromDevice init_value = FROM_DEVICE__INIT;
  *message = init_value;
}

size_t from_device__get_packed_size
    (const FromDevice *message) {
  assert(message->base.descriptor == &from_device__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *) (message));
}

size_t from_device__pack
    (const FromDevice *message,
     uint8_t *out) {
  assert(message->base.descriptor == &from_device__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *) message, out);
}

size_t from_device__pack_to_buffer
    (const FromDevice *message,
     ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &from_device__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *) message, buffer);
}

FromDevice *
from_device__unpack
    (ProtobufCAllocator *allocator,
     size_t len,
     const uint8_t *data) {
  return (FromDevice *)
      protobuf_c_message_unpack(&from_device__descriptor,
                                allocator, len, data);
}

void from_device__free_unpacked
    (FromDevice *message,
     ProtobufCAllocator *allocator) {
  assert(message->base.descriptor == &from_device__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *) message, allocator);
}

static const ProtobufCEnumValue baud_rate__rate__enum_values_by_number[10] =
    {
        {"K1000", "BAUD_RATE__RATE__K1000", 0},
        {"K800",  "BAUD_RATE__RATE__K800",  1},
        {"K500",  "BAUD_RATE__RATE__K500",  2},
        {"K250",  "BAUD_RATE__RATE__K250",  3},
        {"K125",  "BAUD_RATE__RATE__K125",  4},
        {"K100",  "BAUD_RATE__RATE__K100",  5},
        {"K83",   "BAUD_RATE__RATE__K83",   6},
        {"K50",   "BAUD_RATE__RATE__K50",   7},
        {"K20",   "BAUD_RATE__RATE__K20",   8},
        {"AUTO",  "BAUD_RATE__RATE__AUTO",  9},
    };
static const ProtobufCIntRange baud_rate__rate__value_ranges[] = {
    {0, 0},
    {0, 10}
};
static const ProtobufCEnumValueIndex baud_rate__rate__enum_values_by_name[10] =
    {
        {"AUTO",  9},
        {"K100",  5},
        {"K1000", 0},
        {"K125",  4},
        {"K20",   8},
        {"K250",  3},
        {"K50",   7},
        {"K500",  2},
        {"K800",  1},
        {"K83",   6},
    };
const ProtobufCEnumDescriptor baud_rate__rate__descriptor =
    {
        PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
        "BaudRate.Rate",
        "Rate",
        "BaudRate__Rate",
        "",
        10,
        baud_rate__rate__enum_values_by_number,
        10,
        baud_rate__rate__enum_values_by_name,
        1,
        baud_rate__rate__value_ranges,
        NULL, NULL, NULL, NULL   /* reserved[1234] */
    };
static const ProtobufCFieldDescriptor baud_rate__field_descriptors[1] =
    {
        {
            "rate",
            1,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_ENUM,
            offsetof(BaudRate, has_rate),
            offsetof(BaudRate, rate),
            &baud_rate__rate__descriptor,
            NULL,
            0,             /* flags */
            0, NULL, NULL    /* reserved1,reserved2, etc */
        },
    };
static const unsigned baud_rate__field_indices_by_name[] = {
    0,   /* field[0] = rate */
};
static const ProtobufCIntRange baud_rate__number_ranges[1 + 1] =
    {
        {1, 0},
        {0, 1}
    };
const ProtobufCMessageDescriptor baud_rate__descriptor =
    {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "BaudRate",
        "BaudRate",
        "BaudRate",
        "",
        sizeof(BaudRate),
        1,
        baud_rate__field_descriptors,
        baud_rate__field_indices_by_name,
        1, baud_rate__number_ranges,
        (ProtobufCMessageInit) baud_rate__init,
        NULL, NULL, NULL    /* reserved[123] */
    };
static const ProtobufCEnumValue frame__ide__enum_values_by_number[2] =
    {
        {"STD", "FRAME__IDE__STD", 0},
        {"EXT", "FRAME__IDE__EXT", 4},
    };
static const ProtobufCIntRange frame__ide__value_ranges[] = {
    {0, 0},
    {4, 1},
    {0, 2}
};
static const ProtobufCEnumValueIndex frame__ide__enum_values_by_name[2] =
    {
        {"EXT", 1},
        {"STD", 0},
    };
const ProtobufCEnumDescriptor frame__ide__descriptor =
    {
        PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
        "Frame.IDE",
        "IDE",
        "Frame__IDE",
        "",
        2,
        frame__ide__enum_values_by_number,
        2,
        frame__ide__enum_values_by_name,
        2,
        frame__ide__value_ranges,
        NULL, NULL, NULL, NULL   /* reserved[1234] */
    };
static const ProtobufCEnumValue frame__rtr__enum_values_by_number[2] =
    {
        {"DATA",   "FRAME__RTR__DATA",   0},
        {"REMOTE", "FRAME__RTR__REMOTE", 2},
    };
static const ProtobufCIntRange frame__rtr__value_ranges[] = {
    {0, 0},
    {2, 1},
    {0, 2}
};
static const ProtobufCEnumValueIndex frame__rtr__enum_values_by_name[2] =
    {
        {"DATA",   0},
        {"REMOTE", 1},
    };
const ProtobufCEnumDescriptor frame__rtr__descriptor =
    {
        PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
        "Frame.RTR",
        "RTR",
        "Frame__RTR",
        "",
        2,
        frame__rtr__enum_values_by_number,
        2,
        frame__rtr__enum_values_by_name,
        2,
        frame__rtr__value_ranges,
        NULL, NULL, NULL, NULL   /* reserved[1234] */
    };
static const ProtobufCFieldDescriptor frame__field_descriptors[5] =
    {
        {
            "id",
            1,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_INT32,
            offsetof(Frame, has_id),
            offsetof(Frame, id),
            NULL,
            NULL,
            0,             /* flags */
            0, NULL, NULL    /* reserved1,reserved2, etc */
        },
        {
            "dlc",
            2,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_INT32,
            offsetof(Frame, has_dlc),
            offsetof(Frame, dlc),
            NULL,
            NULL,
            0,             /* flags */
            0, NULL, NULL    /* reserved1,reserved2, etc */
        },
        {
            "ide",
            3,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_ENUM,
            offsetof(Frame, has_ide),
            offsetof(Frame, ide),
            &frame__ide__descriptor,
            NULL,
            0,             /* flags */
            0, NULL, NULL    /* reserved1,reserved2, etc */
        },
        {
            "rtr",
            4,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_ENUM,
            offsetof(Frame, has_rtr),
            offsetof(Frame, rtr),
            &frame__rtr__descriptor,
            NULL,
            0,             /* flags */
            0, NULL, NULL    /* reserved1,reserved2, etc */
        },
        {
            "data",
            5,
            PROTOBUF_C_LABEL_REPEATED,
            PROTOBUF_C_TYPE_BYTES,
            offsetof(Frame, n_data),
            offsetof(Frame, data),
            NULL,
            NULL,
            0,             /* flags */
            0, NULL, NULL    /* reserved1,reserved2, etc */
        },
    };
static const unsigned frame__field_indices_by_name[] = {
    4,   /* field[4] = data */
    1,   /* field[1] = dlc */
    0,   /* field[0] = id */
    2,   /* field[2] = ide */
    3,   /* field[3] = rtr */
};
static const ProtobufCIntRange frame__number_ranges[1 + 1] =
    {
        {1, 0},
        {0, 5}
    };
const ProtobufCMessageDescriptor frame__descriptor =
    {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "Frame",
        "Frame",
        "Frame",
        "",
        sizeof(Frame),
        5,
        frame__field_descriptors,
        frame__field_indices_by_name,
        1, frame__number_ranges,
        (ProtobufCMessageInit) frame__init,
        NULL, NULL, NULL    /* reserved[123] */
    };
static const ProtobufCEnumValue to_device__message_type__enum_values_by_number[6] =
    {
        {"SEND_FRAME",   "TO_DEVICE__MESSAGE_TYPE__SEND_FRAME",   0},
        {"INIT",         "TO_DEVICE__MESSAGE_TYPE__INIT",         1},
        {"DEINIT",       "TO_DEVICE__MESSAGE_TYPE__DEINIT",       2},
        {"SET_FILTER",   "TO_DEVICE__MESSAGE_TYPE__SET_FILTER",   3},
        {"SET_BAUDRATE", "TO_DEVICE__MESSAGE_TYPE__SET_BAUDRATE", 4},
        {"GET_STATUS",   "TO_DEVICE__MESSAGE_TYPE__GET_STATUS",   5},
    };
static const ProtobufCIntRange to_device__message_type__value_ranges[] = {
    {0, 0},
    {0, 6}
};
static const ProtobufCEnumValueIndex to_device__message_type__enum_values_by_name[6] =
    {
        {"DEINIT",       2},
        {"GET_STATUS",   5},
        {"INIT",         1},
        {"SEND_FRAME",   0},
        {"SET_BAUDRATE", 4},
        {"SET_FILTER",   3},
    };
const ProtobufCEnumDescriptor to_device__message_type__descriptor =
    {
        PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
        "ToDevice.MessageType",
        "MessageType",
        "ToDevice__MessageType",
        "",
        6,
        to_device__message_type__enum_values_by_number,
        6,
        to_device__message_type__enum_values_by_name,
        1,
        to_device__message_type__value_ranges,
        NULL, NULL, NULL, NULL   /* reserved[1234] */
    };
static const ProtobufCFieldDescriptor to_device__field_descriptors[4] =
    {
        {
            "type",
            1,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_ENUM,
            offsetof(ToDevice, has_type),
            offsetof(ToDevice, type),
            &to_device__message_type__descriptor,
            NULL,
            0,             /* flags */
            0, NULL, NULL    /* reserved1,reserved2, etc */
        },
        {
            "id",
            2,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_INT32,
            offsetof(ToDevice, has_id),
            offsetof(ToDevice, id),
            NULL,
            NULL,
            0,             /* flags */
            0, NULL, NULL    /* reserved1,reserved2, etc */
        },
        {
            "frame",
            3,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE,
            0,   /* quantifier_offset */
            offsetof(ToDevice, frame),
            &frame__descriptor,
            NULL,
            0,             /* flags */
            0, NULL, NULL    /* reserved1,reserved2, etc */
        },
        {
            "baudRate",
            4,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE,
            0,   /* quantifier_offset */
            offsetof(ToDevice, baudrate),
            &baud_rate__descriptor,
            NULL,
            0,             /* flags */
            0, NULL, NULL    /* reserved1,reserved2, etc */
        },
    };
static const unsigned to_device__field_indices_by_name[] = {
    3,   /* field[3] = baudRate */
    2,   /* field[2] = frame */
    1,   /* field[1] = id */
    0,   /* field[0] = type */
};
static const ProtobufCIntRange to_device__number_ranges[1 + 1] =
    {
        {1, 0},
        {0, 4}
    };
const ProtobufCMessageDescriptor to_device__descriptor =
    {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "ToDevice",
        "ToDevice",
        "ToDevice",
        "",
        sizeof(ToDevice),
        4,
        to_device__field_descriptors,
        to_device__field_indices_by_name,
        1, to_device__number_ranges,
        (ProtobufCMessageInit) to_device__init,
        NULL, NULL, NULL    /* reserved[123] */
    };
static const ProtobufCFieldDescriptor response__field_descriptors[2] =
    {
        {
            "ok",
            1,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_BOOL,
            offsetof(Response, has_ok),
            offsetof(Response, ok),
            NULL,
            NULL,
            0,             /* flags */
            0, NULL, NULL    /* reserved1,reserved2, etc */
        },
        {
            "error",
            2,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_STRING,
            0,   /* quantifier_offset */
            offsetof(Response, error),
            NULL,
            NULL,
            0,             /* flags */
            0, NULL, NULL    /* reserved1,reserved2, etc */
        },
    };
static const unsigned response__field_indices_by_name[] = {
    1,   /* field[1] = error */
    0,   /* field[0] = ok */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
    {
        {1, 0},
        {0, 2}
    };
const ProtobufCMessageDescriptor response__descriptor =
    {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "Response",
        "Response",
        "Response",
        "",
        sizeof(Response),
        2,
        response__field_descriptors,
        response__field_indices_by_name,
        1, response__number_ranges,
        (ProtobufCMessageInit) response__init,
        NULL, NULL, NULL    /* reserved[123] */
    };
static const ProtobufCFieldDescriptor status__field_descriptors[1] =
    {
        {
            "rate",
            1,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_ENUM,
            offsetof(Status, has_rate),
            offsetof(Status, rate),
            &baud_rate__rate__descriptor,
            NULL,
            0,             /* flags */
            0, NULL, NULL    /* reserved1,reserved2, etc */
        },
    };
static const unsigned status__field_indices_by_name[] = {
    0,   /* field[0] = rate */
};
static const ProtobufCIntRange status__number_ranges[1 + 1] =
    {
        {1, 0},
        {0, 1}
    };
const ProtobufCMessageDescriptor status__descriptor =
    {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "Status",
        "Status",
        "Status",
        "",
        sizeof(Status),
        1,
        status__field_descriptors,
        status__field_indices_by_name,
        1, status__number_ranges,
        (ProtobufCMessageInit) status__init,
        NULL, NULL, NULL    /* reserved[123] */
    };
static const ProtobufCEnumValue from_device__message_type__enum_values_by_number[3] =
    {
        {"GET_FRAME", "FROM_DEVICE__MESSAGE_TYPE__GET_FRAME", 0},
        {"STATUS",    "FROM_DEVICE__MESSAGE_TYPE__STATUS",    1},
        {"RESPONSE",  "FROM_DEVICE__MESSAGE_TYPE__RESPONSE",  2},
    };
static const ProtobufCIntRange from_device__message_type__value_ranges[] = {
    {0, 0},
    {0, 3}
};
static const ProtobufCEnumValueIndex from_device__message_type__enum_values_by_name[3] =
    {
        {"GET_FRAME", 0},
        {"RESPONSE",  2},
        {"STATUS",    1},
    };
const ProtobufCEnumDescriptor from_device__message_type__descriptor =
    {
        PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
        "FromDevice.MessageType",
        "MessageType",
        "FromDevice__MessageType",
        "",
        3,
        from_device__message_type__enum_values_by_number,
        3,
        from_device__message_type__enum_values_by_name,
        1,
        from_device__message_type__value_ranges,
        NULL, NULL, NULL, NULL   /* reserved[1234] */
    };
static const ProtobufCFieldDescriptor from_device__field_descriptors[5] =
    {
        {
            "type",
            1,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_ENUM,
            offsetof(FromDevice, has_type),
            offsetof(FromDevice, type),
            &from_device__message_type__descriptor,
            NULL,
            0,             /* flags */
            0, NULL, NULL    /* reserved1,reserved2, etc */
        },
        {
            "id",
            2,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_INT32,
            offsetof(FromDevice, has_id),
            offsetof(FromDevice, id),
            NULL,
            NULL,
            0,             /* flags */
            0, NULL, NULL    /* reserved1,reserved2, etc */
        },
        {
            "frame",
            3,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE,
            0,   /* quantifier_offset */
            offsetof(FromDevice, frame),
            &frame__descriptor,
            NULL,
            0,             /* flags */
            0, NULL, NULL    /* reserved1,reserved2, etc */
        },
        {
            "response",
            4,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE,
            0,   /* quantifier_offset */
            offsetof(FromDevice, response),
            &response__descriptor,
            NULL,
            0,             /* flags */
            0, NULL, NULL    /* reserved1,reserved2, etc */
        },
        {
            "status",
            5,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_MESSAGE,
            0,   /* quantifier_offset */
            offsetof(FromDevice, status),
            &status__descriptor,
            NULL,
            0,             /* flags */
            0, NULL, NULL    /* reserved1,reserved2, etc */
        },
    };
static const unsigned from_device__field_indices_by_name[] = {
    2,   /* field[2] = frame */
    1,   /* field[1] = id */
    3,   /* field[3] = response */
    4,   /* field[4] = status */
    0,   /* field[0] = type */
};
static const ProtobufCIntRange from_device__number_ranges[1 + 1] =
    {
        {1, 0},
        {0, 5}
    };
const ProtobufCMessageDescriptor from_device__descriptor =
    {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "FromDevice",
        "FromDevice",
        "FromDevice",
        "",
        sizeof(FromDevice),
        5,
        from_device__field_descriptors,
        from_device__field_indices_by_name,
        1, from_device__number_ranges,
        (ProtobufCMessageInit) from_device__init,
        NULL, NULL, NULL    /* reserved[123] */
    };
